### ISSUE TITLE
How to query a font's ascent/descent?

### ISSUE THREAD

**Issue by r4dr3fr4d** [python-xlib/python-xlib#193]
I can't seem to figure out how to use the request objects, in which I think the answer lies.  Trying to do the equivalent of an XLoadQueryFont in C, which returns a structure with 'ascent' and 'descent' fields.

**Comment by petli** [comment]
You should normally not need to use the request objects, since they implement the low-level wire protocol. Instead there are classes with methods that provide a higher-level interface.  In this case you probably want to use `Fontable.query()` (https://python-xlib.github.io/python-xlib_22.html#Fontable). The font object can be accessed through `Display.open_font()`.

**Comment by r4dr3fr4d** [comment]
Thank you!
