### ISSUE TITLE
Can't find an equivalent for XMoveWindow and XResizeWindow

### ISSUE THREAD

**Issue by J-E-Mc** [python-xlib/python-xlib#197]
I looked through the source code and i can't seem to find an equivalent to the XMoveWindow and XResizeWindow calls

**Comment by benoit-pierre** [comment]
You can use [`configure`](https://github.com/python-xlib/python-xlib/blob/master/Xlib/xobject/drawable.py#L407)([request details](https://github.com/python-xlib/python-xlib/blob/master/Xlib/protocol/request.py#L154)) I believe.

**Comment by petli** [comment]
Yes, any `move_window` and `resize_window` would just be wrappers around `configure`. I think I never bothered adding them since a configure call is easy to use in python-xlib compared to C Xlib, so from that point there's less need for the wrappers. But if it helps mapping documenation from C Xlib, they would have a purpose. I expect that a PR for that would be merged.
